name: release

on: 
  push:
    tags:
      - "v*.*.*"

env:
  DOTNET_VERSION: '8.0.202'

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller
        python -m pip install install -r requirements.txt
    
    - name: Build
      run: |
        .\release.bat
        $ZIP_PATH = "${{ github.workspace }}\dist\wintimeweatherteller.${{ github.ref_name }}.win-x64.zip"
        move dist.zip "$ZIP_PATH"
        $ZIP_PATH = $ZIP_PATH -replace '\\','/'
        echo "ZIP_PATH=$ZIP_PATH" >> $env:GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564 # v2.0.4
      with:
        files:
          ${{ env.ZIP_PATH }}